# Generated by Django 2.2.5 on 2022-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('typebridge', models.CharField(max_length=45)),
                ('actualmtu', models.CharField(max_length=45)),
                ('l2mtu', models.CharField(max_length=45)),
                ('vlan', models.BooleanField(default=False)),
                ('bridge_id', models.CharField(max_length=45)),
            ],
        ),
    ]
