# Generated by Django 2.2.5 on 2022-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='ethernet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ether_id', models.CharField(max_length=45)),
                ('ether_name', models.CharField(max_length=45)),
                ('mac_address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_id', models.CharField(max_length=45)),
                ('interface_name', models.CharField(max_length=45)),
                ('typeinterface', models.CharField(max_length=45)),
                ('actualmtu', models.CharField(max_length=45)),
                ('l2mtu', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlanid', models.CharField(max_length=45)),
                ('vlan_name', models.CharField(max_length=45)),
                ('vlan_id', models.CharField(max_length=45)),
                ('vlan_interface', models.CharField(max_length=45)),
            ],
        ),
    ]
