# Generated by Django 2.2.5 on 2022-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_ethernet_interface_vlan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethernet',
            name='ether_type',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlan',
            name='vlan_type',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
