# Generated by Django 2.2.5 on 2022-04-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220424_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethernet',
            old_name='ether_type',
            new_name='ether_default',
        ),
    ]
