# Generated by Django 2.2.5 on 2022-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20220424_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='vlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlansid', models.CharField(max_length=45)),
                ('vlans_bridge', models.CharField(max_length=45)),
                ('vlans_ids', models.CharField(max_length=45)),
                ('tagged', models.CharField(max_length=45)),
                ('untagged', models.CharField(max_length=45)),
            ],
        ),
    ]
