# Generated by Django 2.2.5 on 2022-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_vlans_tagged1'),
    ]

    operations = [
        migrations.CreateModel(
            name='dhcpclient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhcp_id', models.CharField(max_length=45)),
                ('interface', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('gateway', models.CharField(max_length=45)),
                ('dns', models.CharField(max_length=45)),
                ('ntp', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='dhcpnetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhcp_id', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('gateway', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='dhcpserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhcp_id', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('interface', models.CharField(max_length=45)),
                ('address_pool', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ipaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('network', models.CharField(max_length=45)),
                ('interface', models.CharField(max_length=45)),
                ('dynamic', models.CharField(max_length=45)),
            ],
        ),
    ]
