# Generated by Django 2.2.5 on 2022-04-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_dhcpclienttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(max_length=45)),
                ('pool_name', models.CharField(max_length=45)),
                ('pool_address', models.CharField(max_length=45)),
            ],
        ),
    ]
