# Generated by Django 2.2.5 on 2022-04-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpnetwork',
            name='dns',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
