# Generated by Django 2.2.5 on 2022-04-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_dhcpnetwork_dns'),
    ]

    operations = [
        migrations.CreateModel(
            name='dhcplease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhcp_id', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('mac_address', models.CharField(max_length=45)),
                ('client', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('dhcpserver', models.CharField(max_length=45)),
            ],
        ),
    ]
