# Generated by Django 2.2.5 on 2022-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_dhcplease'),
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=45)),
                ('dst_address', models.CharField(max_length=45)),
                ('gateway', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('dynamic', models.CharField(max_length=45)),
            ],
        ),
    ]
