# Generated by Django 2.2.5 on 2022-04-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='dynamic',
            new_name='distance',
        ),
    ]
