# Generated by Django 2.2.5 on 2022-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20220427_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('group', models.CharField(max_length=45)),
            ],
        ),
    ]
