# Generated by Django 2.2.5 on 2022-04-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_identity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='dns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=45)),
                ('dynamic', models.CharField(max_length=45)),
                ('allow', models.CharField(max_length=45)),
            ],
        ),
    ]
