# Generated by Django 2.2.5 on 2022-04-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_dns'),
    ]

    operations = [
        migrations.CreateModel(
            name='connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_id', models.CharField(max_length=45)),
                ('protocal', models.CharField(max_length=45)),
                ('src', models.CharField(max_length=45)),
                ('dst', models.CharField(max_length=45)),
                ('reply_src', models.CharField(max_length=45)),
                ('reply_dst', models.CharField(max_length=45)),
                ('repl_byte', models.IntegerField(max_length=45)),
                ('repl_packet', models.IntegerField(max_length=45)),
                ('orig_packet', models.IntegerField(max_length=45)),
                ('orig_byte', models.IntegerField(max_length=45)),
            ],
        ),
    ]
