# Generated by Django 2.2.5 on 2022-04-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='orig_byte',
            field=models.IntegerField(max_length=60),
        ),
        migrations.AlterField(
            model_name='connection',
            name='orig_packet',
            field=models.IntegerField(max_length=60),
        ),
        migrations.AlterField(
            model_name='connection',
            name='repl_byte',
            field=models.IntegerField(max_length=60),
        ),
        migrations.AlterField(
            model_name='connection',
            name='repl_packet',
            field=models.IntegerField(max_length=60),
        ),
        migrations.AlterField(
            model_name='connection',
            name='reply_dst',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='connection',
            name='reply_src',
            field=models.CharField(max_length=60),
        ),
    ]
