# Generated by Django 2.2.5 on 2022-04-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20220429_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='orig_byte',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='connection',
            name='orig_packet',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='connection',
            name='repl_byte',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='connection',
            name='repl_packet',
            field=models.CharField(max_length=60),
        ),
    ]
