# Generated by Django 2.2.5 on 2022-04-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_auto_20220429_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(max_length=45)),
                ('binding_mac', models.CharField(max_length=45)),
                ('binding_ser', models.CharField(max_length=45)),
                ('binding_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('server', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=45)),
                ('server_name', models.CharField(max_length=45)),
                ('server_interface', models.CharField(max_length=45)),
                ('server_pool', models.CharField(max_length=45)),
                ('server_profile', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='serverprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_profile', models.CharField(max_length=45)),
                ('ser_name', models.CharField(max_length=45)),
                ('ser_address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userpro_id', models.CharField(max_length=45)),
                ('userpro_name', models.CharField(max_length=45)),
                ('userpro_address', models.CharField(max_length=45)),
                ('userpro_share', models.CharField(max_length=45)),
                ('userpro_rate', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_pass',
        ),
        migrations.AddField(
            model_name='user',
            name='user_pro',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_ser',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
