# Generated by Django 2.2.5 on 2022-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_auto_20220429_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotspotuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('user_ser', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('user_pass', models.CharField(max_length=45)),
                ('user_pro', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_pass',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_pro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_ser',
        ),
    ]
