# Generated by Django 2.2.5 on 2022-04-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_auto_20220429_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='binding',
        ),
        migrations.DeleteModel(
            name='host',
        ),
        migrations.DeleteModel(
            name='hotspotuser',
        ),
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
