# Generated by Django 2.2.5 on 2022-04-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_auto_20220429_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotspotuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('user_ser', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('user_pass', models.CharField(max_length=45)),
                ('user_pro', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userpro_id', models.CharField(max_length=45)),
                ('userpro_name', models.CharField(max_length=45)),
                ('userpro_address', models.CharField(max_length=45)),
                ('userpro_share', models.CharField(max_length=45)),
                ('userpro_rate', models.CharField(max_length=45)),
            ],
        ),
    ]
