# Generated by Django 2.2.5 on 2022-04-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_hotspotuser_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(max_length=45)),
                ('binding_mac', models.CharField(max_length=45)),
                ('binding_ser', models.CharField(max_length=45)),
                ('binding_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('server', models.CharField(max_length=45)),
            ],
        ),
    ]
