# Generated by Django 2.2.5 on 2022-04-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_binding_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='address',
            new_name='host_address',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='mac_address',
            new_name='host_mac_address',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='server',
            new_name='host_server',
        ),
    ]
