# Generated by Django 2.2.5 on 2022-04-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_auto_20220429_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprofile',
            name='ser_id',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
