# Generated by Django 2.2.5 on 2022-04-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_serverprofile_ser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverprofile',
            name='ser_profile',
        ),
    ]
