# Generated by Django 2.2.5 on 2022-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_auto_20220501_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='binding',
            name='binding_address',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
