# Generated by Django 2.2.5 on 2022-05-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_binding_binding_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='dynamic',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
